
#While running the jar file give three arguments batchDate (DD-MM-YYYY), server code ( 00 for all servers, 01 for NSE ,...), config file path


server.port=8085

#NAS CredentialsdcHost = 172.29.3.27
dcUser = mohds
dcPass = Ntick@2026

drHost = 172.29.3.27
drUser = mohds
drPass = Ntick@2026


no_of_threads=1

#kindly keep department name same as in application.json file
email.Inspection=auditninspection@ncdex.com
email.Enforcement=enforcementgroup@ncdex.com
email.Membership=membership@ncdex.com
email.CSG=customerservice@ncdex.com


email.Subject=Files status 


#Config Paths  Either give single forward slash "/" or double backslash "\\"
path.emailConfig=C:/Users/int30/eclipse-workspace/Sft/configFiles/Email.properties
path.filesBody=C:\\Users\\int30\\eclipse-workspace\\Sft\\configFiles\\EmailBodies\\FilesMissingAndFound.txt
path.connectionBody=C:\\Users\\int30\\eclipse-workspace\\Sft\\configFiles\\EmailBodies\\ConnectionError.txt

path.departmentDetails=C:\\Users\\int30\\eclipse-workspace\\Sft\\configFiles\\temp.json
path.SFTPServer=C:/Users/int30/eclipse-workspace/Sft/configFiles/SFTPServer.json
path.local_folder_temporary=C:\\Users\\int30\\eclipse-workspace\\Sft\\configFiles

path.log4j2=C:\\Users\\int30\\eclipse-workspace\\Sft\\configFiles\\log4j2.xml


# Trigger Folders
trigger.folder.Inspection=/yash shukla/File_Transfer_Test/Inspection/Trigger
trigger.folder.Enforcement=/yash shukla/File_Transfer_Test/Enforcement/Trigger
trigger.folder.Membership=/yash shukla/File_Transfer_Test/Membership/Trigger
trigger.folder.CSG=/yash shukla/File_Transfer_Test/CSG/Trigger



