#EMAIL_URL=http://192.168.213.160/EmailGateway/EmailService.asmx
EMAIL_URL=http://172.29.51.74/EmailGateway/EmailService.asmx
FROM_EMAIL_ID=nse_dev@ncdex.com
TO_EMAIL_ID=yash.shukla@ncdex.com
TXN_ID=691509
EMAIL_SENT_SUCCESS=<Description>Success</Description>
MAIL_USERID=VERTICAUSR
MAIL_PASSWORD=Welcome@123
MAIL_USERID=MDMADM
MAIL_PASSWORD=mdm@1234
SHORT_CODE=VNVSSS
SHORT_CODE=MDM
COMPAIGN_Y=N
EMAIL_SERVER=172.29.51.74
PORT=21

NCDEX_FROM_EMAIL_ID=yash.shukla@ncdex.com
FTP_USERID=VERTICAUSR
FTP_PASSWORD=Welcome@123

